### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by yuniorcf-80** [DevelopmentalImagingMCRI/MCRIBS#2]
Hi, thanks for sharing such an amazing tool.
I have managed to run the software by using the following syntax:
"MCRIBReconAll -all --subjectage 44 ID0104 --openmp 8"
However I am interested to use my GPU but I do not know how to write the command line. 
Syntaxes like 
"MCRIBReconAll -all --subjectage 44 ID0105 -use-gpu"  or 
"MCRIBReconAll -all --subjectage 44 ID0105 --use-gpu"  or 
"MCRIBReconAll -all -use-gpu --subjectage 44 ID0105"
 raises the following error: "MCRIBReconAll: error: unrecognized arguments: --use-gpu"

Could you please provide me a clue about it?

In addition I would like to provide a list os patients. I wonder whether that is possible?
Thanks in advance

**Comment by chrisadamsonmcri** [comment]
Thank you.

The GPU portion has essentially been deprecated and removed since it was removed in Freesurfer 7. So just stick to the CPU version.

You can't provide a list of subjects to a single MCRIBReconAll since it only processes one subject at a time. You will need to loop through subjects yourself.

**Comment by yuniorcf-80** [comment]
Dear @chrisadamsonmcri, thank you for your kind and quick response. Although it is bad news the pipeline performance is not that bad in my 8-cores CPU. 

Thank you once again
